### ISSUE TITLE
How to add contributor to list?

### ISSUE THREAD

**Issue by goldbergyoni** [goldbergyoni/javascript-testing-best-practices#106]
@js-kyle Layman question - when I approve John Doe's PR, will he be added automatically to the list or should I do anything manual?

**Comment by js-kyle** [comment]
It isn't fully automated - when you want to add a contributor, you request the bot to add them by mentioning it in an issue comment, by using the command

@all-contributors-bot please add @goldbergyoni for content

https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/CONTRIBUTING.md#other-contributions-

**Comment by js-kyle** [comment]
It seems the bot isn't working as it should today :(

I will try it again soon - there might be an outage to the service

**Comment by js-kyle** [comment]
@all-contributors-bot please add @goldbergyoni for content

**Comment by goldbergyoni** [comment]
OK, let me try

@all-contributors-bot please add @js-kyle for content

**Comment by goldbergyoni** [comment]
That's easy, even I can do this. Ping once it's up again and I'll add the latest contributos

**Comment by js-kyle** [comment]
Does the bot still have access to the repository? It is a bit strange it isn't working anymore

**Comment by js-kyle** [comment]
@all-contributors-bot please add @goldbergyoni for content

**Comment by js-kyle** [comment]
@all-contributors please add @goldbergyoni for content

**Comment by js-kyle** [comment]
Okay @goldbergyoni I just had the command wrong the whole time 😅

I can see you've worked this out out - it works the same way as on the nodebestpractices repo
