### ISSUE TITLE
Few small typos

### ISSUE THREAD

**Issue by mbiesiad** [goldbergyoni/javascript-testing-best-practices#117]
Hi, few small typos to correct:
(first row - original, second - recommended version)

2.1
white*check_mark
white_check_mark

```
*_all
_all_
```
-*_ vs _

Cindy Sridharan suggests a rich testing portfolio in her amazing post ‘Testing Microservices—the sane way
(...) same (...)
-same vs sane

some fear. and fear will slow you down
(...) , and (...)
-not dot

Great job!
Best greetings

**Comment by goldbergyoni** [comment]
@mbiesiad Many thanks, you have keen eyes for details :)

I'll edit those in my next PR, or if you happen to have some time to put this in PR it could be great

**Comment by mbiesiad** [comment]
My pleasure! Fantastic. Looks great. Issue could be closed 🔥
