### ISSUE TITLE
Portuguese (BR) Translation

### ISSUE THREAD

**Issue by luisangelorjr** [goldbergyoni/javascript-testing-best-practices#149]
Hi! Thanks for all content here!

I can start a pt-br translation?
What's the best first step?

**Comment by henriquelbsouza** [comment]
I think it is already there: https://github.com/goldbergyoni/javascript-testing-best-practices/blob/master/readme-pt-br.md

**Comment by luisangelorjr** [comment]
Hi @henriquelbsouza thanks!

I opened a pull request to add the link to readme.md and list the contributors

**Comment by goldbergyoni** [comment]
@luisangelorjr Cool 🔥, looking now

**Comment by luisangelorjr** [comment]
Very nice <3
