### ISSUE TITLE
Section 5.6 has wrong text for Do and Otherwise

### ISSUE THREAD

**Issue by shadowspawn** [goldbergyoni/javascript-testing-best-practices#20]
Great coverage and content, thanks!

I noticed section [5.6](https://github.com/goldbergyoni/javascript-testing-best-practices/#-%EF%B8%8F56-constantly-inspect-for-vulnerable-dependencies) incorrectly starts with the first paragraph from section [5.5](https://github.com/goldbergyoni/javascript-testing-best-practices/#-%EF%B8%8F55-stay-away-from-legal-issues-using-license-and-plagiarism-check) and then the intended text appears in the "otherwise":

> ✅ Do: Licensing and plagiarism issues are probably not your main concern right now, but why not tick this box as well in 10 minutes? A bunch of npm packages like license check and plagiarism check (commercial with free plan) can be easily baked into your CI pipeline and inspect for sorrows like dependencies with restrictive licenses or code that was copy-pasted from Stackoverflow and apparently violates some copyrights 

> ❌ Otherwise: Even the most reputable dependencies such as Express have known vulnerabilities. This can get easily tamed using community tools such as npm audit, or commercial tools like snyk (offer also a free community version). Both can be invoked from your CI on every build

**Comment by shadowspawn** [comment]
Looks like an off-by-one as [Node.js & JavaScript Testing Best Practices (2019)](https://medium.com/@me_37286/yoni-goldberg-javascript-nodejs-testing-best-practices-2b98924c9347) has

> ✅ Do: Even the most reputable dependencies such as Express have known vulnerabilities. This  can get easily tamed using community tools such as npm audit, or commercial tools like snyk  (offer also a free community version). Both can be invoked from your CI on every build

> ❎ Otherwise: Keeping your code clean from vulnerabilities without dedicated tools will require to constantly follow online publications about new threats. Quite tedious

**Comment by goldbergyoni** [comment]
Welcome aboard and Great catch.

Many thanks for the help.

I shall be back home from a trip tomorrow and process all PRs/issues 🙏

**Comment by goldbergyoni** [comment]
@shadowspawn Great catch. Thanks man. If you wanna PR the change - this would be helpful. But no worries, I can do this as well soon.

p.s. I didn't manage to link to the bullets (the TOC is clickable), you also saved that problem 😆
