### ISSUE TITLE
Translate pt-Br

### ISSUE THREAD

**Issue by iagocavalcante** [goldbergyoni/javascript-testing-best-practices#32]
Can i translate this repo to pt-Br?

**Comment by js-kyle** [comment]
Exciting idea @iagocavalcante! Yoni will be back from break shortly to respond, I am sure he will be interested 👍

**Comment by goldbergyoni** [comment]
@iagocavalcante  Welcome aboard! Having a Brazilian Portuguese translation would be awesome 🔥🌈👌 . I'll be glad to collaborate with you on this and help wherever I can

Before you start with this, I've prepared some basic workflow guidelines:

**Where to do the translation?** - Fork and work your own copy, create a readme-{language}.md file (e.g. readme-fr.md) and do the translation work over there

**How to push changes?** - I will create a dedicated branch for you translations-{language}-staging (e.g. translations-fr-staging), whenever you want to save some changes or share with the team - just PR to this branch

**How & when to publish to master?** - The content can be published once it's 70% translated and 100% language proofed. Kindly run it through spell checker. Whenever you feel that the content stands to these guidelines, just a raise a flag and I'll merge the language branch into the master

**Will I get credit for the translation work?** - Obviously! Your name will appear nearby the language flag in the main readme.md, added to the repo team, appear boldly at the top of the translation page - 'Translated, adapted and reviewed by {Your name}'. We will also publish a medium article with the translation with your name at the top

Looking forward and excited to work on this!

**Comment by iagocavalcante** [comment]
Thanks @goldbergyoni, that's an interesting workflow! I'll start this job in this week, thanks for the amazing work with this project!

**Comment by goldbergyoni** [comment]
@iagocavalcante That's just a proposed workflow, feel free to adjust

**Comment by iagocavalcante** [comment]
I'm back, today i'll do more progress

**Comment by leandromuto** [comment]
@iagocavalcante @goldbergyoni I would like to help if possible.

**Comment by iagocavalcante** [comment]
Off course, can your fork my fork and send a pr ?

**Comment by leandromuto** [comment]
@iagocavalcante yes, I'll send asap. Thanks :)

**Comment by brunopenso** [comment]
@iagocavalcante I can't find your PR to check, but the link on the readme.MD file points out to pt-br is missing.

**Comment by brunopulis** [comment]
Hey @iagocavalcante I wish I could help translate, is there anything I can do?

**Comment by iagocavalcante** [comment]
I'll close this issue because it's already done. To catch portuguese translation, click[here](https://github.com/goldbergyoni/javascript-testing-best-practices/blob/master/readme-pt-br.md)
