### ISSUE TITLE
Can I translate this repo to ko-KR?

### ISSUE THREAD

**Issue by icepeng** [goldbergyoni/javascript-testing-best-practices#33]
Awesome writing!

**Comment by js-kyle** [comment]
@icepeng Nice idea! Yoni is back from break soon - I'm sure he will be interested 👍

**Comment by goldbergyoni** [comment]
@icepeng  Welcome aboard! Having a Korean translation would be awesome 🔥🌈👌 . I'll be glad to collaborate with you on this and help wherever I can

Before you start with this, I've prepared some basic workflow guidelines:

**Where to do the translation?** - Fork and work your own copy, create a readme-{language}.md file (e.g. readme-fr.md) and do the translation work over there

**How to push changes?** - I will create a dedicated branch for you translations-{language}-staging (e.g. translations-fr-staging), whenever you want to save some changes or share with the team - just PR to this branch

**How & when to publish to master?** - The content can be published once it's 70% translated and 100% language proofed. Kindly run it through spell checker. Whenever you feel that the content stands to these guidelines, just a raise a flag and I'll merge the language branch into the master

**Will I get credit for the translation work?** - Obviously! Your name will appear nearby the langauge flag in the main readme.md, added to the repo team, appear boldly at the top of the translation page - 'Translated, adapted and reviewed by {Your name}'. We will also publish a medium article with the translation with your name at the top

Looking forward and excited to work on this!
