### ISSUE TITLE
THANKS FOR MAKING THIS 🔥

### ISSUE THREAD

**Issue by AmoDinho** [goldbergyoni/javascript-testing-best-practices#35]
Hi @goldbergyoni,

Would really like to say thanks for making this resource! Every other resource for learning how to write tests really sucks!

What you've made on the other hand is a real game changer! 🔨

**Comment by js-kyle** [comment]
@AmoDinho awesome feedback 😃! Yoni will be back from break soon - he will be happy to see this I'm sure!

**Comment by goldbergyoni** [comment]
@AmoDinho Many thanks for writing this, I indeed spent a long time with customers at the testing trenches and then long time on writing this text. Hearing that it actually helped someone justifies the energy :)

Appreciate your kind words 🙏

**Comment by AmoDinho** [comment]
@goldbergyoni Your energy was most definitely justified, because I was absolutely  hopeless with regards to testing. This has definitely made it possible to embrace TDD, especially the way in which the examples are coupled with the explanations. 💃 

Once again thanks! 🥇
