### ISSUE TITLE
Shield/Badges with wrong title or in wrong place

### ISSUE THREAD

**Issue by DouglasMV** [goldbergyoni/javascript-testing-best-practices#70]
I have already made a PR on this #69 but i suspect there are more Badges with wrong titles.
Also i think some of the badges are in the wrong code examples.
For example in the pratice [3.4](https://github.com/goldbergyoni/javascript-testing-best-practices#-%EF%B8%8F-34-dont-sleep-use-frameworks-built-in-support-for-async-events-also-try-to-speed-things-up) the first example has React and React Testing Library Badges but it is actually a Cypher example.

I would fix it but i'm not sure which ones are correct or not. Maybe someone with more experience should take a look.

**Comment by goldbergyoni** [comment]
@DouglasMV All your fixes there are correct and very helpful, thanks a bunch!
